baseURL = 'http://localhost/center/it/new/'
languageCode = 'ja-jp'
title = '鳴門教育大学 情報基盤センター'
theme = ["ananke"]

hasCJKLanguage = true

# From ananke theme/config.toml
resourceDir = "../resources"

DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
enableRobotsTXT = true

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 10 # this is set low for demonstrating with dummy content. Set to a higher number

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"

[params]
    text_color = ""
    author = ""
    favicon = "https://www.naruto-u.ac.jp/center/it/img/logo.gif"
    site_logo = ""
    description = "鳴門教育大学 情報基盤センターの公式 Web サイトです．"
    # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
    background_color_class = "bg-indigo"
    # choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
    featured_image_class = "cover bg-top"
    # choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
    cover_dimming_class = "bg-black-60"
    recent_posts_number = 5
    recent_top_news = 10

    custom_css = ["naruto.css"]
    body_classes = "jpfonts bg-near-white"
    post_content_classes = "jpfonts"
    date_format = "2006/01/02"

    CustomSearchId = "1038c374a3d07623e"

[markup.goldmark.parser.attribute]
    block = true
